name: Build MySQL Plugin

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive  # Menarik semua submodule secara rekursif

    - name: Install C++ compiler and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libmysqlclient-dev libboost-all-dev

    - name: Create build directory and run CMake
      run: |
        mkdir -p SA-MP-MySQL/build
        cd SA-MP-MySQL/build
        cmake ..

    - name: Build the project
      run: |
        cd SA-MP-MySQL/build
        make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: mysql-plugin-build
        path: SA-MP-MySQL/build
